
        <!-- Marketing Icons Section -->
        <div class="row">

            <div class="col-lg-12">
                <div class="jumbotron" id="jumbotron-about">
                    <h1>Welcome to Film Exchange</h1>
                    <p>Where Thy Films held art seeds, thy films shared art flowers</p>
                    <p><a class="btn btn-danger btn-lg" href="/gallery" role="button">View Gallery</a></p>
                </div>
            </div>

            <div class="col-lg-12">
                <h1 class="page-header">
                    Explore Film Exchange
                </h1>
            </div>
            <div class="col-md-4">
                <div class="panel panel-danger">
                    <div class="panel-heading">
                        <h4><i class="fa fa-fw fa-check"></i>Stunning Videos</h4>
                    </div>
                    <div class="panel-body">
                        <p>Whether you are a designer, a coder, a video maker… if you need film clips for your exciting projects, Film Exchange is the best place for you to find short video clips. Simply search with different categories, you will be able to find the one you want within seconds.
                        </p>
                        <a href="/pricing" class="btn btn-warning">Learn More</a>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="panel panel-danger">
                    <div class="panel-heading">
                        <h4><i class="fa fa-fw fa-gift"></i>Amazing Quality</h4>
                    </div>
                    <div class="panel-body">
                        <p>With over 10,000 videos (we can change the number, this is for commercial use…) that support from 240px resolution to 4K resolution, and extremely polished sound effects, implementing short film clips into your projects will be a revolutionary experience!
                        </p>
                        <a href="/gallery" class="btn btn-warning">Learn More</a>
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="panel panel-danger">
                    <div class="panel-heading">
                        <h4><i class="fa fa-fw fa-gift"></i>Innovative Service</h4>
                    </div>
                    <div class="panel-body">
                        <p>Not sure what you are looking for, or not sure which film clip is the best one for you? Worry not! Our legendary service team is willing to help you at any time! With masters and senseis in the film and design industry, we are able to provide you with expert suggestions.
                        </p>
                        <button class="learnmore btn btn-warning">More Services</button>

                        <div  id="close-button" class="col-lg-6">
                            <ul class="list-group services-list" >
                                <?php 

                                 ?>
                            </ul>
                            
                        </div>

                    </div>
                </div>
            </div>
        </div>
        <!-- /.row -->