<div class="row">

	<div class="col-lg-12">
		<h1 class="page-header">Contact Page</h1>
	</div>
<div class="col-lg-8">
                <!-- Embedded Google Map -->
                <div id="map" style="width:100%;height:400px;"></div>
            </div>
            <!-- Contact Details Column -->
            <div class="col-lg-4">
                <h3>Contact Details</h3>
                <p>
                    3481 Melrose Place<br>Beverly Hills, CA 90210<br>
                </p>
                <p><i class="fa fa-phone"></i> 
                    <abbr title="Phone">P</abbr>: (123) 456-7890</p>
                <p><i class="fa fa-envelope-o"></i> 
                    <abbr title="Email">E</abbr>: <a href="mailto:name@example.com">contact@filmexchange.com</a>
                </p>
                <p><i class="fa fa-clock-o"></i> 
                    <abbr title="Hours">H</abbr>: Monday - Friday: 9:00 AM to 5:00 PM</p>
                <ul class="list-unstyled list-inline list-social-icons">
                    <li>
                        <a href="#"><i class="fa fa-facebook-square fa-2x"></i></a>
                    </li>
                    <li>
                        <a href="#"><i class="fa fa-linkedin-square fa-2x"></i></a>
                    </li>
                    <li>
                        <a href="#"><i class="fa fa-twitter-square fa-2x"></i></a>
                    </li>
                    <li>
                        <a href="#"><i class="fa fa-google-plus-square fa-2x"></i></a>
                    </li>
                </ul>
            </div>
</div>

<div class="row" id="row-form">
	<div class="col-lg-8">
		<form class="form-horizontal" action="/contact" method="post">
		  <div class="form-group">
		    <label for="exampleInputEmail1">Name</label>
		    <input type="text" name="name" class="form-control" id="exampleInputEmail1" placeholder="your name">
		  </div>
		  <div class="form-group">
		    <label for="exampleInputPassword1">Email address</label>
		    <input type="email" name="email" class="form-control" id="exampleInputPassword1" placeholder="email address">
		  </div>
		  <div class="form-group">
		    <textarea class="form-control" name="comment" rows="3" placeholder="write your message here"></textarea>
		  </div>

		  <button type="submit" class="btn btn-danger" id="contact-but">Submit</button>
		</form>
	</div>

	<div class="col-lg-4">
		<?php
			if($this->message == '') {
				echo '<p>
						<br/>
						It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using "Content here, content here"
					</p>';
			} else {
				echo $this->message;
				echo '<br/>';
				echo $this->email;
			}
		?>
	</div>

</div>