        <div class="row">

            <div class="col-lg-12">
                <h1 class="page-header">
                <?php 
                    if(isset($this->id)){
                    $id = $this->id;
                    // var_dump($this->videos[$id]);
                    echo $this->videos[$id]["title"];
                   }
                   // echo "<pre>";     
                   // var_dump($this->id);
                ?>
                </h1>
            </div>

            <div class="col-lg-12 col-md-12 col-xs-12">
                
                    <!-- <img class="img-responsive" src="http://placehold.it/1920x1080" alt="video#1"> -->
                    <video poster = <?php 
                                    if(isset($this->id)){
                                        $id = $this->id;
                                        echo $this->videos[$id]["poster"];
                                    }?> class="img-responsive" controls>
                    <source src = <?php 
                        if(isset($this->id)){
                            echo $this->videos[$id]["url"];
                        }?> type="video/mp4">
                </video>
            </div>

            <div class="col-lg-12 col-md-12 col-xs-12" style="margin-top:50px">


                    <!-- Video Description -->
                    <p>
                    <?php
                     if(isset($this->id)){
                        
                        echo $this->videos[$id]["description"];
                       }
                    ?>
                    </p>

                    <?php 
                    
                    $prev_id = $id-1;
                    $next_id = $id+1;

                    if ($prev_id<=-1) {
                        $prev_id = 11;
                    }

                    if ($next_id>=12) {
                        $next_id = 0;
                    }

                    
                    echo '<a href="/gallery/details?id='. $prev_id . '"> <button type="button" class="btn btn-default">Previous</button> </a>
                          <a href="/gallery/details?id='. $next_id . '"> <button type="button" class="btn btn-default">Next</button> </a>
                          '
                    ?>

            </div>
            
           
        </div>