        <div class="row">

            <div class="col-lg-12">
                <h1 class="page-header">Gallery</h1>
            </div>

            <div class="col-lg-3 col-md-4 col-xs-6 thumb">
                <a class="thumbnail" href="/gallery/details?id=0">
                    <img class="img-responsive" src="../thumbs/ju-inspiration.jpg" alt="Ju Inspiration Video">
                </a>
            </div>
            <div class="col-lg-3 col-md-4 col-xs-6 thumb">
                <a class="thumbnail" href="/gallery/details?id=1">
                    <img class="img-responsive" src="../thumbs/keep-rolling.jpg" alt="Keep Rolling Video">
                </a>
            </div>
            <div class="col-lg-3 col-md-4 col-xs-6 thumb">
                <a class="thumbnail" href="/gallery/details?id=2">
                    <img class="img-responsive" src="../thumbs/julia-redherring.jpg" alt="Julia Redherring Video">
                </a>
            </div>
            <div class="col-lg-3 col-md-4 col-xs-6 thumb">
                <a class="thumbnail" href="/gallery/details?id=3">
                    <img class="img-responsive" src="../thumbs/ufo.jpg" alt="UFO Video by Sejin">
                </a>
            </div>
            <div class="col-lg-3 col-md-4 col-xs-6 thumb">
                <a class="thumbnail" href="/gallery/details?id=4">
                    <img class="img-responsive" src="../thumbs/mum.jpg" alt="You are not a plastic spoon Video by Sejin">
                </a>
            </div>
            <div class="col-lg-3 col-md-4 col-xs-6 thumb">
                <a class="thumbnail" href="/gallery/details?id=5">
                    <img class="img-responsive" src="../thumbs/thronehall.jpg" alt="Throne Hall Video by Horhe">
                </a>
            </div>
            <div class="col-lg-3 col-md-4 col-xs-6 thumb">
                <a class="thumbnail" href="/gallery/details?id=6">
                    <img class="img-responsive" src="../thumbs/acupofwine.jpg" alt="A cup of wine Video by Horhe">
                </a>
            </div>
            <div class="col-lg-3 col-md-4 col-xs-6 thumb">
                <a class="thumbnail" href="/gallery/details?id=7">
                    <img class="img-responsive" src="../thumbs/bouldermobilefxf.jpg" alt="Boulder Mobile fxf Video by Horhe">
                </a>
            </div>
            <div class="col-lg-3 col-md-4 col-xs-6 thumb">
                <a class="thumbnail" href="/gallery/details?id=8">
                    <img class="img-responsive" src="../thumbs/anim-resume.jpg" alt="Animation Resume Video by Tiago">
                </a>
            </div>
            <div class="col-lg-3 col-md-4 col-xs-6 thumb">
                <a class="thumbnail" href="/gallery/details?id=9">
                    <img class="img-responsive" src="../thumbs/lettersfromjapan.jpg" alt="Letters from Japan Video by Horhe">
                </a>
            </div>
            <div class="col-lg-3 col-md-4 col-xs-6 thumb">
                <a class="thumbnail" href="/gallery/details?id=10">
                    <img class="img-responsive" src="../thumbs/fourdesign.jpg" alt="Four Design video by Four Design Group Project">
                </a>
            </div>
            <div class="col-lg-3 col-md-4 col-xs-6 thumb">
                <a class="thumbnail" href="/gallery/details?id=11">
                    <img class="img-responsive" src="../thumbs/comicsfifi.jpg" alt="Comics FiFi by Horhe and Angel">
                </a>
            </div>
        </div>