<!-- <div class="full"></div>

<div class="row" style="margin-top:55vh;">

    <div class="col-lg-12">
        <h1 class="page-header">Film Exchange</h1>
    </div>

    <div class="col-lg-12">
        <p>
        What is Lorem Ipsum?
        Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
        </p>
        <p>
        What is Lorem Ipsum?
        Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.
        </p> -->
   
<video id="home-video" autoplay poster="/img/home-poster.jpg" loop>
  <!-- WCAG general accessibility recommendation is that media such as background video play through only once. Loop turned on for the purposes of illustration; if removed, the end of the video will fade in the same way created by pressing the "Pause" button  -->
<source src="/video/home.mp4" type="video/mp4">
</video>

    <div class="row" id="index-content">
        <div class="col-lg-12">
            <h1 id="home-h1">Welcome to Film Exchange</h1>

            <p class="home-p">Once upon a time, a group gave life to a platform. And there came the most beautiful movie clips of the realm. Now, a well-crafted site, whose goal is to deliver customers with quality products and outstanding service. Welcome to Film Exchange, Where Thy Films held art seeds, thy films shared art flowers.</p>
            
            <p class="home-p">Film Exchange is a platform where users can find carefully designed and captured videos and implement them on their projects, movies, films, etc. Based in Beautiful Vancouver, British Columbia, our goal is to deliver a clean, safe and fun experience and provide users with a fast and convenient way to find video clips they are looking for. We believe film making is a way of feeling, of touching, of loving. What you have caught on film is captured forever... it remembers little things, long after you have forgotten everything. At Film Exchange, we plant these seeds of love, and when shared, they bloom and vitalize.</p>

        </div>
    </div>

<!-- End of row div -->
</div> 