<div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">Pricing
                </h1>
<!--                 <ol class="breadcrumb">
                    <li><a href="index.html">Home</a>
                    </li>
                    <li class="active">Pricing Table</li>
                </ol> -->
            </div>
        <!-- /.row -->

            <div class="col-lg-12">
                <div class="jumbotron" id="jumbotron-pricing">
                    <h3>Get 10 videos a month for as low as $40 CAD with our most affordable subscriptions ever.</h3>
                </div>
            </div>
            <div class="col-md-6">
                <div class="panel panel-danger text-center">
                    <div class="panel-heading">
                        <h3 class="panel-title">Pay per download with credits</h3>
                    </div>
                    <div class="panel-body">
                        <span class="price"><sup>$</sup>19<sup>99</sup></span>
                        <span class="period">per month</span>
                    </div>
                    <ul class="list-group">
                        <li class="list-group-item"><strong>1</strong> User</li>
                        <li class="list-group-item"><strong>5</strong> Projects</li>
                        <li class="list-group-item"><strong>Unlimited</strong> Email Accounts</li>
                        <li class="list-group-item"><strong>10GB</strong> Disk Space</li>
                        <li class="list-group-item"><strong>100GB</strong> Monthly Bandwidth</li>
                        <li class="list-group-item"><a href="http://filmexchange.jorged-gonzalez.com/contact" class="btn btn-danger">Sign Up!</a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="col-md-6">
                <div class="panel panel-danger text-center">
                    <div class="panel-heading">
                        <h3 class="panel-title">Subscription <!-- <span class="label label-success">Best Value</span> --></h3>
                    </div>
                    <div class="panel-body">
                        <span class="price"><sup>$</sup>40</span>
                        <span class="period">per month</span>
                    </div>
                    <ul class="list-group">
                        <li class="list-group-item"><strong>10</strong> Videos</li>
                        <li class="list-group-item"><strong>500</strong> Projects</li>
                        <li class="list-group-item"><strong>Unlimited</strong> Email Accounts</li>
                        <li class="list-group-item"><strong>1000GB</strong> Disk Space</li>
                        <li class="list-group-item"><strong>10000GB</strong> Monthly Bandwidth</li>
                        <li class="list-group-item"><a href="http://filmexchange.jorged-gonzalez.com/contact" class="btn btn-danger">Sign Up!</a>
                        </li>
                    </ul>
                </div>
            </div>
<!--             <div class="col-md-4">
                <div class="panel panel-default text-center">
                    <div class="panel-heading">
                        <h3 class="panel-title">Ultra</h3>
                    </div>
                    <div class="panel-body">
                        <span class="price"><sup>$</sup>159<sup>99</sup></span>
                        <span class="period">per month</span>
                    </div>
                    <ul class="list-group">
                        <li class="list-group-item"><strong>Unlimted</strong> Users</li>
                        <li class="list-group-item"><strong>Unlimited</strong> Projects</li>
                        <li class="list-group-item"><strong>Unlimited</strong> Email Accounts</li>
                        <li class="list-group-item"><strong>10000GB</strong> Disk Space</li>
                        <li class="list-group-item"><strong>Unlimited</strong> Monthly Bandwidth</li>
                        <li class="list-group-item"><a href="#" class="btn btn-primary">Sign Up!</a>
                        </li>
                    </ul>
                </div>
            </div> -->
</div>
        <!-- /.row -->